name: Workflow - Build all crates

on:
  push:

jobs:
  split-crates:
    name: Prepare crate list
    runs-on: ubuntu-latest
    outputs:
      crates: ${{ steps.env.outputs.crates }}
    steps:
      - name: Checkout Bevy
        uses: actions/checkout@v4
        with:
          repository: bevyengine/bevy
          ref: main
      - name: Prepare crate list
        id: env
        run: |
          crate_list=`cargo test -p 2>&1 | grep '  bevy'`
          echo "crates=`python3 -c \"import json; crate_list='''$crate_list''';print(json.dumps([crate.strip() for crate in crate_list.splitlines()]))\"`" >> $GITHUB_OUTPUT

  build-crates:
    name: Build Crate
    needs: [split-crates]
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        crate: ${{ fromJSON(needs.split-crates.outputs.crates) }}

    steps:
      - name: Checkout Bevy
        uses: actions/checkout@v4
        with:
          repository: bevyengine/bevy
          ref: main

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Install Bevy dependencies
        run: |
          sudo apt-get update;
          DEBIAN_FRONTEND=noninteractive sudo apt-get install --no-install-recommends -yq libasound2-dev libudev-dev libxkbcommon-x11-0;

      - name: Build Crate
        run: |
          cargo build -p ${{ matrix.crate }}
