name: Upkeep - Update Cache

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  build-cache:
    name: Build Cache
    runs-on: ubuntu-latest
    strategy:
      matrix:
        extra: ["", "--all-features", "--no-default-features"]

    steps:
      - name: Checkout Bevy main branch
        uses: actions/checkout@v4
        with:
          repository: "bevyengine/bevy"

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Install Bevy dependencies
        run: |
          sudo apt-get update;
          DEBIAN_FRONTEND=noninteractive sudo apt-get install --no-install-recommends -yq libasound2-dev libudev-dev libxkbcommon-x11-0 libwayland-dev

      - name: Build an example (Linux)
        run: cargo build ${{ matrix.extra }}

      - name: Save cache
        uses: actions/cache/save@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: cargo-${{ matrix.extra }}-${{ hashFiles('**/Cargo.toml') }}
